version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
        #執行AWS認證
      - $(aws ecr get-login --no-include-email --registry-ids 'ECR ID' --region ap-northeast-1)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - sh build.sh
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
        #從ECR中最新版本的Dockerfile
      - docker push 'ECR ID'.dkr.ecr.ap-northeast-1.amazonaws.com/ 'ECR Repo' :latest
